In [32]:
import numpy as np
import pandas as pd

In [33]:
suspects = ('gadzi', 'annie', 'ren')
utensils = ('spoon', 'fork', 'chopsticks')

# making everything uniform...
prior_probs = np.array([1/3, 1/3, 1/3])
gadzi_probs = np.array([1/3, 1/3, 1/3])
annie_probs = np.array([1/3, 1/3, 1/3])
ren_probs = np.array([1/3, 1/3, 1/3])

In [34]:
def draw_prior(suspects, probs):
    return np.random.choice(suspects, p=probs)

def draw_model(utensils, suspect, gadzi_probs, annie_probs, ren_probs):
    if (suspect == 'gadzi'):
        return np.random.choice(utensils, p=gadzi_probs)

    elif (suspect == 'annie'):
        return np.random.choice(utensils, p=annie_probs)

    else:
        return np.random.choice(utensils, p=ren_probs)

def draw_joint(utensils, suspects, prior_probs, gadzi_probs, annie_probs, ren_probs):
    s = draw_prior(suspects, prior_probs)
    w = draw_model(utensils, s, gadzi_probs, annie_probs, ren_probs)
    return f"{s}_{w}"

def simulator(*args, num_sims=10000):
    return [draw_joint(*args) for _ in range(num_sims)]

In [35]:
for i in range(5):
  num_sims = 10**i

  sims = simulator(utensils, suspects, prior_probs, gadzi_probs, annie_probs, ren_probs, num_sims=num_sims)

  scenarios, counts = np.unique(sims, return_counts=True)

  print(f"num_sims = {num_sims}:")
  for s, c in zip(scenarios, counts):
    print(f'{s} occurred with a probability of {round(c / num_sims, 2)}.')

  print("\n\n")

num_sims = 1:
ren_fork occurred with a probability of 1.0.



num_sims = 10:
annie_fork occurred with a probability of 0.1.
annie_spoon occurred with a probability of 0.3.
gadzi_chopsticks occurred with a probability of 0.1.
gadzi_fork occurred with a probability of 0.1.
gadzi_spoon occurred with a probability of 0.2.
ren_fork occurred with a probability of 0.1.
ren_spoon occurred with a probability of 0.1.



num_sims = 100:
annie_chopsticks occurred with a probability of 0.14.
annie_fork occurred with a probability of 0.09.
annie_spoon occurred with a probability of 0.12.
gadzi_chopsticks occurred with a probability of 0.07.
gadzi_fork occurred with a probability of 0.09.
gadzi_spoon occurred with a probability of 0.11.
ren_chopsticks occurred with a probability of 0.11.
ren_fork occurred with a probability of 0.13.
ren_spoon occurred with a probability of 0.14.



num_sims = 1000:
annie_chopsticks occurred with a probability of 0.11.
annie_fork occurred with a probability of 0.1.
annie_spoon occurred with a probability of 0.11.
gadzi_chopsticks occurred with a probability of 0.13.
gadzi_fork occurred with a probability of 0.11.
gadzi_spoon occurred with a probability of 0.11.
ren_chopsticks occurred with a probability of 0.12.
ren_fork occurred with a probability of 0.1.
ren_spoon occurred with a probability of 0.11.



num_sims = 10000:
annie_chopsticks occurred with a probability of 0.11.
annie_fork occurred with a probability of 0.11.
annie_spoon occurred with a probability of 0.11.
gadzi_chopsticks occurred with a probability of 0.12.
gadzi_fork occurred with a probability of 0.11.
gadzi_spoon occurred with a probability of 0.12.
ren_chopsticks occurred with a probability of 0.11.
ren_fork occurred with a probability of 0.11.
ren_spoon occurred with a probability of 0.11.

In [43]:
# converting scenario counts into probabilities...
freqs = counts / num_sims
scenario_to_p = dict(zip(scenarios, freqs))

# making the table with rows being suspects and cols being utensils...
sim_joint = np.zeros((len(suspects), len(utensils)))

for i, s in enumerate(suspects):
  for j, w in enumerate(utensils):
    sim_joint[i, j] = scenario_to_p.get(f"{s}_{w}", 0.0)


# simulated joint table...
sim_df = pd.DataFrame(sim_joint, index=suspects, columns=utensils)
print(f"Simulated joint table (N={num_sims}):")
display(sim_df)

Simulated joint table (N=10000):

        spoon    fork  chopsticks
gadzi  0.1174  0.1087      0.1154
annie  0.1107  0.1110      0.1083
ren    0.1101  0.1093      0.1091

In [41]:
# forming analytic joint table...
analytic_joint = np.full((len(suspects), len(utensils)), 1/9)
analytic_df = pd.DataFrame(analytic_joint, index=suspects, columns=utensils)

print("Analytic joint table:")
display(analytic_df)

Analytic joint table:

          spoon      fork  chopsticks
gadzi  0.111111  0.111111    0.111111
annie  0.111111  0.111111    0.111111
ren    0.111111  0.111111    0.111111

In [40]:
# calculating "error" btwn both tables...
abs_err_df = (sim_df - analytic_df).abs()

print("Absolute error |sim - analytic|:")
display(abs_err_df)

print("Max absolute error:", abs_err_df.to_numpy().max())

Absolute error |sim - analytic|:

          spoon      fork  chopsticks
gadzi  0.006289  0.002411    0.004289
annie  0.000411  0.000111    0.002811
ren    0.001011  0.001811    0.002011